---
- name: Install ntp service.
  become: yes
  yum: pkg=httpd state=latest

- name: Enable Apache
  service: name=httpd state=started enabled=yes
  notify: restart apache
  handlers:
- name: restart apache
  service: name=httpd state=restarted