---
 - name: Install Apache Webserver
   yum: pkg=httpd state=latest
 - name: Enable Apache on system reboot
   service: name=httpd enabled=yes
 - name: Install python3
   yum: pkg=python3 state=latest

 - name: Print HOST
   debug:
     msg: "{{ lookup('env', 'TOWER_HOST') }}"
 - name: Print USER
   debug:
     msg: "{{ lookup('env', 'USER') }}"
 - name: Print PASSWORD
   debug:
     msg: "{{ lookup('env', 'HOME') }}"
