---
 - name: Install Apache Webserver
   yum: pkg=httpd state=latest
 - name: Enable Apache on system reboot
   service: name=httpd enabled=yes
 - name: Install python3
   yum: pkg=python3 state=latest
 - name: Print car
   debug: msg="{{ lookup('env','car') }}"
 - name: Print hostvars
   debug: msg="{{ hostvars['localhost'] }}"
